### ISSUE TITLE
System.InvalidOperationException: Cannot provide a value for property 'DocumentService' on type 'BlazorAppWithAuth.App'. There is no registered service of type 'Blorc.Services.IDocumentService'.

### ISSUE THREAD

**Issue by gofrogi** [WildGums/Blorc.OpenIdConnect#12]
- [X ] .NET Standard
 - [ X] .NET Core

## Component
Blorc.OpenIdConnect

## Version of Library
v1.0.0-alpha0048

## Version of OS(s) listed above with issue
win 10

## Steps to Reproduce
I'm trying to use the library in a new created Blazor app (preview 4) as described, But the IDocumentService is not found or if @using Blorc.Services included, then can't get over  the mentioned exception.

**Comment by alexfdezsauco** [comment]
Please register Blorc.Core services using this:

         builder.Services.AddBlorcCore();

**Comment by gofrogi** [comment]
can this lib be used with Microsoft.AspNetCore.Components.WebAssembly.Authentication?

**Comment by alexfdezsauco** [comment]
> can this lib be used with Microsoft.AspNetCore.Components.WebAssembly.Authentication?

Yes
