### ISSUE TITLE
Configuration is not yet loaded on AddBlorcOpenIdConnect middleware

### ISSUE THREAD

**Issue by manojdcoder** [WildGums/Blorc.OpenIdConnect#327]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [X] .NET Core

## Component

`AddBlorcOpenIdConnect` middleware

## Version of Library

1.0.0-alpha0746

## Version of OS(s) listed above with issue

Windows 10 / Chrome 104.0.5112.81 

## Steps to Reproduce
1. Run the demo app
2. Put a debugger in within `AddBlorcOpenIdConnect` middleware
3. builder.Configuration is not loaded, no values in the object 

## Expected Behavior

Configuration is loaded from `appsettings.json` and values are readable

## Actual Behavior

Configuration is not loaded yet from `appsettings.json`

**Comment by alexfdezsauco** [comment]
This configuration file is a client-side configuration file `wwwroot\appsettings.json`

We use this all the time like this:

    builder.Services.AddBlorcOpenIdConnect(
        options =>
        {
            builder.Configuration.Bind("IdentityServer", options);
            // TODO; Here you can customize such other values.
        });

Where the configuration file content looks like this:

    {
      "IdentityServer": {
        "ResponseType": "id_token token",
        "Scope": "openid profile demo-api",
        "Authority": "http://localhost:5002/auth/realms/master",
        "ClientId": "demo-app"
      }
    }

**Comment by manojdcoder** [comment]
@alexfdezsauco Appreciate your response and you are right. I have something like following

```
builder.Services.AddBlorcOpenIdConnect(
    options =>
    {
       var applicationSettings = builder.Services.BuildServiceProvider().GetService<IApplicationSettings>();
        // TODO; Here you can customize such other values.
    });
```

```
     public ApplicationSettings(IWebAssemblyHostEnvironment HostEnvironment, IConfiguration Configuration)
        {
         ....
        }
```

The DI for `IConfiguration` only fails here, this is unrelated to this library but appreciate if you have any thoughts on this.

Also, I wondering why only `code` for `ResponseType` is supported and not others?
