### ISSUE TITLE
Component service Factory

### ISSUE THREAD

**Issue by rodiniz** [WildGums/Blorc.OpenIdConnect#38]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [x ] .NET Core

## Version of Library
Last

## Steps to Reproduce
1.Follow the readme

## Expected Behavior
Call idendity server login page

## Actual Behavior

System.InvalidOperationException: Cannot provide a value for property 'ComponentServiceFactory' on type 'TestClient.App'. There is no registered service of type 'Blorc.Services.IComponentServiceFactory'.

**Comment by alexfdezsauco** [comment]
Please register Blorc.Core services.

      builder.Services.AddBlorcCore();

**Comment by rodiniz** [comment]
The app loads. How do I make it redirect to identityserver ? Update the readme file.

**Comment by alexfdezsauco** [comment]
Updated sorry.

**Comment by alexfdezsauco** [comment]
> Thanks. The app loads. How do I make it redirect to identityserver ? Please update the readme file.

Just update the configuration file or initialize correctly the Configuration property of the UserMananger with the expected values. The readme.md includes the configuration file scenario.
