### ISSUE TITLE
logout user after 15-20 min of inactivity

### ISSUE THREAD

**Issue by vitalybrandes** [WildGums/Blorc.OpenIdConnect#397]
The _signoutTimeSpan = args.SignoutTimeSpan;
Its set to 5 second by default.
i cannot find the place where its defined.
Also, can i some how disable auto logout on inactivity?

i would line to logout user after 15-20 min of inactivity, based on parameter in appsetting.json
where to change?

thanks allot
great feature :-)

**Comment by vitalybrandes** [comment]
Found, 
ups
       options.TimeForUserInactivityAutomaticSignout = 1500;
        options.TimeForUserInactivityNotification = 1000;

**Comment by alexfdezsauco** [comment]
You can set the configuration values in this file `wwwroot/appsettings.json`

This file is part of the web app, not from the server-side host.

for instance, you can create a configuration section like this one 

    ...
    "IdentityServer": {
       ...
      "TimeForUserInactivityAutomaticSignout": 1500,
      "TimeForUserInactivityNotification": 1000
    },
    ...

then you can call `AddBlorcOpenIdConnect` like this 

    builder.Services.AddBlorcOpenIdConnect(
                    options =>
                    {
                        builder.Configuration.Bind("IdentityServer", options);
                    });


or you can set the options parameters exactly as you do.

Sorry for the late response.
