### ISSUE TITLE
Add audience or Resource

### ISSUE THREAD

**Issue by vitalybrandes** [WildGums/Blorc.OpenIdConnect#559]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 
I found some new identity provide kinde,
to get audience they asking to send the audience in request
https://kinde.com/docs/build/get-access-token-for-connecting-securely-to-kindes-api/#get-the-access-token-postman-example

Is it possible?

**Comment by alexfdezsauco** [comment]
To the best of our knowledge of the protocol, the audience is requested using the **Scope** parameter from the configuration. We support request audience in this way from the configuration "Scope": "openid profile %API-NAME%". For details, take a look into the demo or the readme.md file. e don't have support for this configuration using audience value as an URL.

**Comment by vitalybrandes** [comment]
> To the best of our knowledge of the protocol, the audience is requested using the **Scope** parameter from the configuration. We support request audience in this way from the configuration "Scope": "openid profile %API-NAME%". For details, take a look at the demo or the readme.md file. We don't have support for this configuration using audience value as a URL.

Can i some how to extent current to support audience?

I am using logto.io for user Auth.
logto.io request "audience" to get access_token.
https://docs.logto.io/docs/recipes/protect-your-api/spring-boot/#configure-application

**Comment by vitalybrandes** [comment]
There ia allot of issue regarding the same in Auth0.
Using there is some solution AdditionalProviderParameters in AddOidcAuthentication
builder.Services.AddOidcAuthentication(options =>
{
    options.ProviderOptions.AdditionalProviderParameters.Add("audience", builder.Configuration["Auth0:Audience"]);
}

https://community.auth0.com/t/blazor-webassembly-apps-with-multiple-audience/70736

**Comment by gao-sun** [comment]
Logto leverages [RFC 8707](https://datatracker.ietf.org/doc/html/rfc8707) for resources. So an extra `resource` parameter is required for the code flow.

**Comment by vitalybrandes** [comment]
@alexfdezsauco 
Can you please check the gao-sun pill request?
Thanks

**Comment by GeertvanHorrik** [comment]
@alexfdezsauco I quickly reviewed, looking forward to hear what you think. As long as this doesn't break existing flow for Keycloak, I don't mind adding this when there are unit tests covering this scenario *and* the docs are updated.

**Comment by alexfdezsauco** [comment]
Sorry for the delay, let me check.

**Comment by GeertvanHorrik** [comment]
@vitalybrandes @gao-sun Just released 1.9.0-beta1 to NuGet. Can you please double check it works for you? Then we can release as stable.

**Comment by gao-sun** [comment]
> @vitalybrandes @gao-sun Just released 1.9.0-beta1 to NuGet. Can you please double check it works for you? Then we can release as stable.

Sure will check it soon.

**Comment by gao-sun** [comment]
@GeertvanHorrik I can confirm the new options work as expected. Now we can fetch a JWT access token from Logto:

<img width="368" alt="image" src="https://github.com/WildGums/Blorc.OpenIdConnect/assets/14722250/c63a60b2-f063-4ca4-adf2-cf1a2a7b895d">

I'll write a tutorial soon.
