### ISSUE TITLE
Why javascript?

### ISSUE THREAD

**Issue by GioviQ** [WildGums/Blorc.OpenIdConnect#85]
Hi, the ultimate aim of Blazor is to replace javascript with C#, so the best way to connect to Identity Server is to use the C# client
https://github.com/IdentityModel/IdentityModel.OidcClient

**Comment by alexfdezsauco** [comment]
You are right. In the moment we implemented this,  we just try to get advantage from the already implemented **browser based** implementation of OpenIDConnect client. This is why we delegate part of the implementation to the existing library https://github.com/IdentityModel/oidc-client-js. Blazor allows javascript interop even when its ultimate goal is replace it. So, it's not a sin.

We will review https://github.com/IdentityModel/IdentityModel.OidcClient but you are also free to do PR here. Are you interested?

**Comment by GioviQ** [comment]
At the moment I'm just working on Blazor stuff here https://github.com/enkodellc/blazorboilerplate
